name: pantheon-desktop
version: git
summary: Pantheon Desktop Environment. 
description: a GTK desktop based on the GNOME software base.
base: core20
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  pantheon-desktop:
    command: bash
    plugs:
       - desktop
       - desktop-legacy
       - gsettings
       - network
       - x11
      
parts:
  pantheon-desktop:
    stage-packages: elementary-desktop
    plugin: addrepo
      
